spring:
  application:
    name: know-hub-ai
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost/know-hub

server:
  port: 8329


