spring:
  application:
    name: know-hub-ai
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${PGVECTOR_USERNAME:postgres}
    password: ${PGVECTOR_PASSWORD:postgres}
    url: jdbc:postgresql://${PGVECTOR_HOST:localhost}/${PGVECTOR_DATABASE:know-hub}
    # 8h待机自动断开数据库连接解决方案
    tomcat:
      max-active: 100
      min-idle: 10
      min-evictable-idle-time-millis: 1800000
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      validation-query: select 1
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  jpa:
    hibernate:
      ddl-auto: create


    show-sql: true
    open-in-view: true
  # api和key分享自：https://pgthinker.me/2023/10/03/196/
  ai:
    openai:
      base-url: https://api.mnzdna.xyz
      api-key: sk-W0KF2fh5BTX3fEUvBf1262B948354c03B079C94956CfD4B5
#      base-url: ${DEFAULT_BASE_URL}
#      api-key: ${DEFAULT_API_KEY}

# MinIO
minio:
  endpoint: ${MINIO_ENDPOINT:http://127.0.0.1:9000/}
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin}
  bucket-name: ${BUCKET_NAME:know-hub}


server:
  port: 8329

# know-hub-ai的配置
know-hub-ai:
  minio-enabled: ${MINIO_DISABLED:false}





