spring:
  application:
    name: know-hub-ai
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost/know-hub

  autoconfigure:
    exclude: org.springframework.ai.autoconfigure.vectorstore.pgvector.PgVectorStoreAutoConfiguration
  servlet:
    multipart:
      max-file-size: 20MB
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: true
  # api和key分享自：https://pgthinker.me/2023/10/03/196/
  ai:
    openai:
      base-url: https://api.mnzdna.xyz
      api-key: sk-W0KF2fh5BTX3fEUvBf1262B948354c03B079C94956CfD4B5
server:
  port: 8329





