spring:
  application:
    name: know-hub-ai
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${PGVECTOR_USERNAME:postgres}
    password: ${PGVECTOR_PASSWORD:postgres}
    url: jdbc:postgresql://${PGVECTOR_HOST:localhost}/${PGVECTOR_DATABASE:know-hub}
    type: com.zaxxer.hikari.HikariDataSource
    # hikari连接池配置
    hikari:
      #连接池名
      pool-name: HikariCP
      #最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认10分钟
      idle-timeout: 600000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒
      connection-timeout: 30000
      # 连接测试query
      connection-test-query: SELECT 1

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  jpa:
    hibernate:
      ddl-auto: create

    show-sql: true
    open-in-view: true
  # api和key分享自：https://pgthinker.me/2023/10/03/196/
  ai:
    openai:
      base-url: ${DEFAULT_BASE_URL:sk-KgvugzpKzki15GFxB72e7782De844b23B3E4Fc6dDf40B29a}
      api-key: ${DEFAULT_API_KEY:https://api.mnzdna.xyz}

# MinIO
minio:
  endpoint: ${MINIO_ENDPOINT:http://127.0.0.1:9010/}
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin}
  bucket-name: ${BUCKET_NAME:know-hub}
server:
  port: 8329
  address: 0.0.0.0
