server:
  port: 8788
  servlet:
    context-path: /api

spring:
  profiles:
    active: dev
  application:
    name: system-app

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost/template_db
    type: com.zaxxer.hikari.HikariDataSource
    # hikari连接池配置
    hikari:
      #连接池名
      pool-name: HikariCP
      #最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认10分钟
      idle-timeout: 600000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒
      connection-timeout: 30000
      # 连接测试query
      connection-test-query: SELECT 1
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

security:
#  下面几个配置使用默认的即可

#  expiration: 86400000 # a day
#  refresh-expiration:
  secret: 123123123
  salt: 123123123
  allow-list:
    - "/v3/**"
    - "/swagger-ui/**"
    - "/doc.html"
    - "/webjars/**"
    - "/auth/login"
  admin-init: true
  password: 123123


knife4j:
  enable: true
  setting:
    language: zh_cn
    enable-open-api: true
    enable-group: true

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: me.pgthinker.system.controller
