version: '3'
services:
  vector_db:
    image: ankane/pgvector:v0.5.0
    container_name: vector_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=know-hub
      - PGPASSWORD=postgres
    volumes:
      - ../sql/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./pg_data/vector_db:/var/lib/postgresql/data
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    healthcheck:
      test: "pg_isready -U postgres -d know-hub"
      interval: 2s
      timeout: 20s
      retries: 10

  minio:
    image: minio/minio:latest
    restart: always
    container_name: permission_minio
    privileged: true
    command: server --address ":9000" --console-address ":9001" ../data
    ports:
      - '9032:9000'
      - '9033:9001'
    volumes:
      - '../config:/root/.minio'
      - '../data:/data'
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123
